version: "3"
services:
  www:
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl

  php-fpm:
    volumes:
      - ./php-fpm/etc/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini # additional php configuration file

  database:
    ports:
      - "33060:3306"
