name: Docker

on:
  push:
    branches: [main, refactor-docker-env]
    tags: ["v*.*"]
  pull_request:
    branches: [main]

env:
  REGISTRY: ghcr.io
  REPO_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # https://github.com/docker/build-push-action
      - name: Build and push php-fpm Docker image
        uses: docker/build-push-action@v2
        env:
          VERSION: ${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
          SERVICE: "php-fpm"
        with:
          file: docker/php-fpm/Dockerfile
          context: ./docker/php-fpm
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ env.REPO_NAME }}-${{ env.SERVICE}}:${{ env.VERSION }}, /${{ env.REPO_NAME }}-${{ env.SERVICE}}:latest
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            "COMPOSER_VERSION=2.1.14"
            "PHP_VERSION=7.4"

      - name: Build and push nginx Docker image
        uses: docker/build-push-action@v2
        env:
          VERSION: ${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
          SERVICE: "nginx"
        with:
          file: docker/nginx/Dockerfile
          context: ./docker/nginx
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ env.REPO_NAME }}-${{ env.SERVICE}}:${{ env.VERSION }}, /${{ env.REPO_NAME }}-${{ env.SERVICE}}:latest
          labels: ${{ steps.meta.outputs.labels }}
